### ISSUE TITLE
Make an element stick to top and bottom!

### ISSUE THREAD

**Issue by mgrubinger** [mgrubinger/blog#6]
---
date: '2020-08-12T08:00:00Z'
published: true
short: Useful CSS to make an element stick to the top and bottom of a scroll container!
tags:
    - TIL
    - CSS
---

It is possible to make an element stick to the top **and** bottom of a scroll container! You could say: "Of course!", but I guess I was just surprised it *actually* works.

Here's the CSS:

```css
.i-am-sticky {
	position: sticky;
	top: 0; /* or any other value if you want some offset */
	bottom: 0; /* or any other value if you want some offset */
}
```

I find this especially useful for a *List/Detail* two-column layout where items in the right column shows details when item in the left column is selected (think Apple Mail etc). 

This way the selected item always stays visible to the user.

(Imagine trying to solve this using JS, urgh.)

### Demo:

Here's a quick demo:

<iframe
     src="https://codesandbox.io/embed/sticky-top-and-bottom-5s9ti?fontsize=14&hidenavigation=1&theme=dark&view=preview"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="sticky-top-and-bottom"
     allow="geolocation; microphone; camera; midi; vr; accelerometer; gyroscope; payment; ambient-light-sensor; encrypted-media; usb"
     sandbox="allow-modals allow-forms allow-popups allow-scripts allow-same-origin"
   ></iframe>
